import { Router } from "express";

import userRoutes from "./userRoutes";
import authRoutes from "./authRoutes";
import settingRoutes from "./settingRoutes";
import contactRoutes from "./contactRoutes";
import ticketRoutes from "./ticketRoutes";
import whatsappRoutes from "./whatsappRoutes";
import messageRoutes from "./messageRoutes";
import whatsappSessionRoutes from "./whatsappSessionRoutes";
import autoReplyRoutes from "./autoReplyRoutes";
import fastReplyRoutes from "./fastReplyRoutes";
import queueRoutes from "./queueRoutes";
import statisticsRoutes from "./statisticsRoutes";
import tagRoutes from "./tagRoutes";
import campaignRoutes from "./campaignRoutes";
import campaignContactsRoutes from "./campaignContactsRoutes";
import apiConfigRoutes from "./apiConfigRoutes";
import apiExternalRoutes from "./apiExternalRoutes";
import chatFlowRoutes from "./chatFlowRoutes";
import tenantRoutes from "./tenantRoutes";
import WebHooksRoutes from "./WebHooksRoutes";
import adminRoutes from "./adminRoutes";
import facebookRoutes from "./facebookRoutes";
import sessionDebugRoutes from "./sessionDebugRoutes";
import callRoutes from "./callRoutes";
import notificationRoutes from "./notificationRoutes";
import reportRoutes from "./reportRoutes";
import businessHoursRoutes from "./businessHoursRoutes";
import groupRoutes from "./groupRoutes";

const routes = Router();

routes.use("/users", userRoutes);
routes.use("/auth", authRoutes);
routes.use("/settings", settingRoutes);
routes.use("/contacts", contactRoutes);
routes.use("/tickets", ticketRoutes);
routes.use("/whatsapp", whatsappRoutes);
routes.use("/messages", messageRoutes);
routes.use("/whatsappsession", whatsappSessionRoutes);
routes.use("/auto-reply", autoReplyRoutes);
routes.use("/fastreply", fastReplyRoutes);
routes.use("/queue", queueRoutes);
routes.use("/statistics", statisticsRoutes);
routes.use("/tags", tagRoutes);
routes.use("/campaigns", campaignRoutes);
routes.use("/campaign-contacts", campaignContactsRoutes);
routes.use("/api-config", apiConfigRoutes);
routes.use("/api-external", apiExternalRoutes);
routes.use("/chat-flow", chatFlowRoutes);
routes.use("/tenants", tenantRoutes);
routes.use("/webhooks", WebHooksRoutes);
routes.use("/admin", adminRoutes);
routes.use("/facebook", facebookRoutes);
routes.use("/session-debug", sessionDebugRoutes);
routes.use("/calls", callRoutes);
routes.use("/notifications", notificationRoutes);
routes.use("/reports", reportRoutes);
routes.use("/business-hours", businessHoursRoutes);
routes.use("/groups", groupRoutes);

export default routes;
